### ISSUE TITLE
A little lost here…

### ISSUE THREAD

**Issue by silvestreh** [diversen/simple-php-translation#1]
I'm trying to follow the README file, but I'm not sure I'm following… Please be aware that I have **VERY LITTLE** knowledge of PHP.

I have a project set up something like this:

```
lang/
--en/language.php
--es/language.php

templates/
--blocks/
----header.php
----[…]
--sections/
----home.php
----[…]

boot.php
index.php // This is where I include my templates and boot.php
```

My `boot.php` goes something like this:

``` php
<?php
include_once(__DIR__ . '/vendor/autoload.php');
$lang = (!empty($_GET['lang'])) ? $_GET['lang'] : 'es';

use diversen\lang;
use diversen\translate\extractor;

$l = new lang();
$l->setDirsInsideDir(__DIR__ . '/lang/');
$l->setDirsInsideDir(__DIR__ . '/templates/');
$l->loadLanguage($lang);

$e = new extractor();
$e->defaultLanguage = $lang;
$e->updateLang();

// This is just a shortcut function
function __($str) {
    return lang::translate($str);
}
```

By including `boot.php` in my "main template", `index.php`, I'd like to add all non-translated strings to their corresponding translation file, but they remain unchanged (ie. nothing is being appended to the translation files)

In my template files I'm using the shortcut function `__()` like so:

``` php
<?= __('Some string to translate'); ?>
```

And I'm seeing them rendered as `NT: Some string to translate`. I assume `NT` stands for `Not Translated` or something along those lines.

My apache error logs are not showing anything…

**Comment by diversen** [comment]
To extract, do like this. 

It is based on `lang::translate` method in my setup, but if 
you just want to extract your own strings using your own method `__` then
this should be possible.  

You have an `index.php` file with this content: 

```
<?php

include_once "vendor/autoload.php";

use diversen\translate\extractor;

$e = new extractor();
$e->extractMethodName = '__'; // THIS is the method you will extract
$e->defaultLanguage ='en'; // which language dir will you extract to, set e.g. 'es'
// $e->setDirsInsideDir('test/'); this dir takes multiple dirs inside a single dir
// The method above is usefull, if you have modules/account modules/blog etc.
// However we start with a single dir
$e->setSingleDir('test');
$e->updateLang();
```

Don't run this yet, you need something to extract: 

You have a dir named `test`

Put this content in e.g. `test.php` inside `test`: 

```
<?php

// Some php file with your method function `__`

echo __('Here is a test');
```

Now run `php index.php` (if your put it on server you will figure out how)

You will end up with a file like this `test/lang/en/language.php` with the following content: 

```
<?php

$LANG = array();

// Translation of file test/test.php

$LANG['Here is a test'] = 'Here is a test';
```

You will need to find a way to load this file yourself, as my system only works automatic is you use a method called `lang::translate`. Then there is a way of loading all this strings per automatic, and then just call `lang::translate('e.g. Translate this')`. 

Hope above explanation is useful :)

**Comment by silvestreh** [comment]
Nope, that's not working for me… What I'm trying to accomplish is that untranslated strings get added to their corresponding translation file.

Suppose the string `Hello World` has no translation and in my template I try to `echo` its Spanish translation. (Remember that my `__` function is just a shortcut to `lang::translate` so I have to type less code in my templates)

``` html
<h1><?= __('Hello World'); ?></h1>
```

I'm expecting `Hello World` to be added in `/lang/es/language.php`. 

If the string `Hello World` has a Spanish translation, then I'd like `__('Hello World')` to return `Hola Mundo`.

Does that make sense?

Thanks

**Comment by diversen** [comment]
If you use the class correct then `untranslated strings get added to their corresponding translation file.` See above example and the documentation and follow these examples. I don't think there is any errors in the classes, you just don't use it correct. See my code example. Important: You will need to change the name of your shortcut method `__` in the extractor class (`$e->extractMethodName = '__';`) as translation is extracted based on regex on a method name. The extractor scans through all files in the directories which you have set up in your project,  finds all content of the first parameter of `lang::translate`, and adds these as key and value pairs to the array in the language.php files. The method name is maybe a bit misleading - as it is used to echo translated strings found in translation files - and also the pattern to search for when extracting. Maybe something like `lang::doEchoFromArrayLoadedFromFilesAndAlsoThePatternToExtractFrom` would be better :)

Most often you will not mix the extraction part with the loading and echoing of translated string. You will just create a shell script and then extract. And then the translation files will be updated. And you should now see the changes on your website or whatever you will be using it for.
