### ISSUE TITLE
setSingleDir path

### ISSUE THREAD

**Issue by stratboy** [diversen/simple-php-translation#4]
Hi! Thank you for your program. It seems I cannot get the translations, though. Where is the path I pass to setSingleDir relative to?

**Comment by diversen** [comment]
It can be both a relative or an absolute path. If it is relative, then it is relative to the executing script. E.g you use the class in index.php: 

     my_project/
     my_project/index.php

Let's say all files with translation live in:

    my_project/App

Then the translation should be placed (and extracted to):

    my_project/App/lang

~~~.php
$l = new Lang();
$l->setSingleDir("App");
// You can also use an absolute path
// $l->setSingleDir("/Users/user/App");
// Load english language
$l->loadLanguage('en');
// This will try to load the file App/lang/en/language.php
~~~

**Comment by stratboy** [comment]
OK thank you!
