### ISSUE TITLE
how can update your google autotranslate for this schemma?

### ISSUE THREAD

**Issue by johnfelipe** [diversen/simple-php-translation#5]
![SNAG-0022](https://user-images.githubusercontent.com/428820/178537485-c08bf8a8-ed60-4256-ac47-64bcbe19852e.png)

```
felipe@ubuntu20:~/simple-php-translation$ php test/google_translate.php
Source file language/lang/en/language.php does not exists. We skip.
```

first php file is

https://gist.github.com/59da4542587164cde2d6109d094b6b50

**Comment by diversen** [comment]
When you try to translate using google, your need access to the source file that should be translated. But the file `language/lang/en/language.php` does not exist. I can also see that you don't use the default `$LANG`, but `$lang`. You will need to set this: 

```php

$t = new GoogleTranslate();

// This is the name of your variable where your translation strings exist (`$lang`)
$t->translateAryName = 'lang';

```

**Comment by johnfelipe** [comment]
https://drive.google.com/file/d/12Znravn7g9p3tlTLQSSTKRrhu9iszNJK/view?usp=drivesdk

pls view that video and give me feedback, i need to translate all php files to spanish, french and italian
Tnks

**Comment by diversen** [comment]
It is your own script that gives the error. Remove the line `defined( 'BASEPATH' ) OR exit( 'No direct script access allowed' );`

Checkout the top of your file: https://gist.github.com/59da4542587164cde2d6109d094b6b50

**Comment by johnfelipe** [comment]
works

**Comment by johnfelipe** [comment]
how can translate all this files, but not rename it?

![SNAG-0022](https://user-images.githubusercontent.com/428820/178537485-c08bf8a8-ed60-4256-ac47-64bcbe19852e.png)

**Comment by diversen** [comment]
It was not made with that specific setup in mind. You could loop over a file at a time - translate it - copy the generated file to the desired location. Something like this:

```php
<?php

use Diversen\Translate\GoogleTranslate;

include_once "vendor/autoload.php";

putenv("GOOGLE_APPLICATION_CREDENTIALS=pebble-2c949028ebcc.json");

// Array of your files to translate
$files = ['files_to_translate/test_1.php', 'files_to_translate/test_2.php'];
foreach ($files as $file) {
    
    copy($file, "lang/en/language.php");    
    
    $t = new GoogleTranslate();

    $t->translateAryName = 'lang';
    $t->target = 'da'; // danish
    $t->source = 'en';

    $t->setSingleDir(".");
    $t->updateLang();

    // You source file should now have been generated. 
    // Copy it with original name to the folder 'files_translated'
    copy ("lang/da/language.php", "files_translated/" . basename($file));
}
```
